version = 0.1

[default.deploy.parameters]
stack_name = "greentrain"
resolve_s3 = true
s3_prefix = "greentrain"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ElectricityMapZone=\"KR\" ThreshGreen=\"400\" ThreshRed=\"600\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-2"
